1. **객체 리터럴에서 ‘this’ 사용하기**
   함수 `makeUser`는 객체를 반환합니다.
   이 객체의 `ref`에 접근하면 어떤 결과가 발생하고, 그 이유는 뭘까요?

```jsx
function makeUser() {
  return {
    name: "John",
    ref: this,
  };
}

let user = makeUser();

alert(user.ref.name); // 결과가 어떻게 될까요?
```

1. **체이닝**
   올라가기(`up`)와 내려가기(`down`) 메서드를 제공하는 객체 `ladder` 가 있습니다.

```jsx
let ladder = {
  step: 0,
  up() {
    this.step++;
  },
  down() {
    this.step--;
  },
  showStep: function () {
    // 사다리에서 몇 번째 단에 올라와 있는지 보여줌
    alert(this.step);
  },
};
```

메서드를 연이어 호출하고자 한다면 아래와 같이 코드를 작성할 수 있습니다.

```jsx
ladder.up();
ladder.up();
ladder.down();
ladder.showStep(); // 1
```

`up`, `down`, `showStep` 을 수정해 아래처럼 메서드 호출 체이닝이 가능하도록 해봅시다.

```jsx
ladder.up().up().down().showStep(); // 1
```

1. **this 값이 undefined인 함수 고치기**
   아래 함수 `askPassword()`는 비밀번호를 먼저 확인하고
   그 결과에 따라 `user.loginOk`나 `user.loginFail`을 호출해야 합니다.
   그런데 함수를 호출하면 에러가 발생합니다. 에러는 왜 발생했을까요?
   에러가 발생하지 않도록 색칠된 줄을 고쳐보세요. 다른 줄은 바꾸지 않아야 합니다.
   힌트 : bind() 메서드 사용

```jsx
function askPassword(ok, fail) {
  let password = prompt("비밀번호를 입력해주세요.", "");
  if (password == "rockstar") ok();
  else fail();
}

let user = {
  name: "John",

  loginOk() {
    alert(`${this.name}님이 로그인하였습니다.`);
  },

  loginFail() {
    alert(`${this.name}님이 로그인에 실패하였습니다.`);
  },
};

askPassword(user.loginOk, user.loginFail); // 색칠된 줄
```
